config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  root 'pages#home'
  get  '/about',   to: 'pages#about'
  resources :users, only: %i(index show)
  resources :items do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :content, presence: true, length: { maximum: 100 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @item = Item.find(params[:item_id])
    @comment = @item.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      render :index
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    if @comment.destroy
      redirect_to  request.referrer || root_url
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/views/comments/_form.html.erb
<%= form_with(model: [item, comment] ) do |form| %>
  <div>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit "コメントをする", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<div class="comments">
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <br>
      <%= link_to "#{comment.user.name}さん", user_path(comment.user) %>
      <p><%= comment.content %></p>
      <% if comment.user == current_user %>
        <%= link_to 'コメントを削除する', item_comment_path(comment.item, comment), method: :delete, remote: true %>
        <br>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
alert("<%= @comment.errors.full_messages %>>")

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.item.comments }) %>")
$("textarea").val('')