config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  root 'pages#home'
  get  '/about',   to: 'pages#about'
  resources :users, only: %i(index show)
  resources :items do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item
  default_scope -> { order(created_at: :desc) }
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 100 },
            uniqueness: { case_sensitive: false }

  def already_liked?(item)
    self.likes.exists?(item_id: item.id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def new
  end

  def edit
  end

  def show
  end

  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected
   def after_update_path_for(resource)
     user_path(current_user)
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :avatar_cache, :remove_avatar])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class  UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items.page(params[:page]).per(5)
  end
end

app/views/users/_user.html.erb
<li>
  <div class="user thumbnail">
    <div class="circle-avatar">
      <% if user.avatar? %>
        <%= image_tag user.avatar.url %>
      <% else %>
        <img src="/images/no_avatar.jpg" alt="Chania">
      <% end %>
    </div>
    <%= link_to user.name, user %>
  </div>
</li>

app/views/users/index.html.erb
<div class="container">
  <br>
  <br>
  <h2>全ユーザー</h2>
  <br>
  <br>
  <div class="row">
    <ol class="users">
      <% @users.each do |user| %>
        <div class="col-12 col-md-3">
          <%= render user %>
        </div>
      <% end %>
    </ol>
  </div>
    <%= paginate @users %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="user_info">
    <br>
    <br>
    <h3><%= @user.name %></h3>
    <div class="circle-avatar">
      <% if @user.avatar? %>
        <%= image_tag @user.avatar.url %>
      <% else %>
        <img src="/images/no_avatar.jpg" alt="Chania">
      <% end %>
    </div>

    <% if @user == current_user %>
      <%= button_to 'プロフィール変更',edit_user_registration_path , method: :get, :class => "btn btn-primary" %>
      <%= button_to '投稿画面',root_path , method: :get, :class => "btn btn-primary" %>
    <% end %>
    <% if current_user.try(:admin?) %>
      <%= button_to '管理画面', rails_admin_path  , method: :get, :class => "btn btn-primary" %>
    <% end %>
  </div>

  <br>
  <br>
  <% if @user.items.any? %>
    <h2>マイアイテム一覧</h2>
  <% else %>
    <h2>まだ投稿したアイテムはありません</h2>
  <% end %>

  <% if @user.items.any? %>
    <div class="row">
      <ol class="items">
        <% @items.each do |item| %>
          <div class="panel panel-default">
            <div class="panel-body">
              <%= render item %>
            </div>
          </div>
        <% end %>
      </ol>
    </div>
    <%= paginate @items %>
  <% end %>
</div>