config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  root 'pages#home'
  get  '/about',   to: 'pages#about'
  resources :users, only: %i(index show)
  resources :items do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { maximum: 200 }
  validates :picture, presence: true
  validate  :picture_size
  mount_uploader :picture, PictureUploader

  private

  def picture_size
    errors.add(:picture, "5MB以下にしてください") if picture.size > 5.megabytes
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :correct_item, only: :destroy
  before_action :set_item, only: %i(show edit update)
  before_action :authenticate_user!, only: %i(index edit update create destroy)

  def index
    @search = Item.ransack(params[:q])
    @result = @search.result.page(params[:page]).per(6)
    @tag_search = Item.tagged_with(params[:tag_list_cont], :any => true)
    @like = Like.new
  end

  def show
    @comment = Comment.new
    @comments = @item.comments
  end

  def edit
  end

  def update
    @item.update!(item_params)
    redirect_to item_path(@item), notice: "投稿を更新しました。"
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:notice] = "投稿が作成されました!"
      redirect_to items_path
    else
      flash[:alert] = "投稿ができませんでした。"
      render "pages/home"
    end
  end

  def destroy
    if @item.user == current_user
      flash[:notice] = "投稿が削除されました" if @item.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to request.referrer || user_path
  end


private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:content, :picture, :tag_list)
  end

  def correct_item
    @item = current_user.items.find_by(id: params[:id])
    redirect_to root_url if @item.nil?
  end
end

app/views/items/_item.html.erb
<div class="items">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="circle-avatar">
        <% if item.user.avatar? %>
          <%= image_tag item.user.avatar.url %>
        <% else %>
          <img src="/images/no_avatar.jpg" alt="Chania">
        <% end %>
      </div>
      <%= link_to  item.user.name, item.user %>
      <br>
      <span class="content">
        <%= simple_format(item.content) %>
      </span>
      <%= link_to(item_path(item)) do %>
        <%= image_tag item.picture.url if item.picture? %>
      <% end %>
      <br>
      <%= render 'items/tag_list', tag_list: item.tag_list %>
      <br>
      <h3>いいね数: <%= item.likes.count %></h3>

      <% if item.user == current_user %>
        <%= link_to '編集', edit_item_path(item) , class: 'btn btn-primary' %>
        <%= link_to "削除", item, method: :delete,
                    class: "btn btn-primary", data: { confirm: "削除してもよろしいですか？？" } %>
      <% end %>
      <span class="timestamp">
        <%= time_ago_in_words(item.created_at) %> 前に投稿されました
      </span>
      <br>
      <div class="comment">
        <div class="comment_area" id="comment_area">
          <%= render 'comments/index', comments: item.comments, item: item %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/_item_form.html.erb
<%= form_for(@item) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "...投稿したいアイテムの写真と紹介文を入れよう！!※※アイテム紹介文と写真はどちらも必須です(タグ登録は任意)※※",
                    class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "タグ登録( ,で区切り複数登録可能)" %>
    <%= f.text_field :tag_list, value: @item.tag_list.join(','), class: "form-control" %>
  </div>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
<% end %>

app/views/items/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="label label-primary"><%= tag %></span>
<% end %>

app/views/items/edit.html.erb
<br>
<br>
<br>
<br>
<%= form_for(@item) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "...投稿したいアイテムの写真と紹介文を入れよう！", class: "form-control" %>
  </div>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
  <%= f.submit "更新する", class: "btn btn-primary" %>
<% end %>

app/views/items/index.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <h2>投稿一覧</h2>
  <br>
  <%= search_form_for @search  do |f| %>
    <div class="form-group">
      <%= f.label :content_cont,  "アイテム検索" %>
      <%= f.text_field :content_cont, class: "form-control", placeholder: "検索したいキーワードを入力して下さい" %>
    </div>
    <div class="actions"><%= f.submit "キーワード検索する" %></div>
  <% end %>
  <div class="form-group">
    <%= form_tag('/items', :method => :get) do %>
      <%= text_field_tag :tag_list_cont,'', placeholder: '検索したいタグを入力して下さい', class: "form-control" %>
      <%= submit_tag 'タグ検索する', class: "form-control" %>
    <% end %>
  </div>
  <br>
  <br>

  <div class="row">
    <ol class="items">
      <div class="panel panel-default">
          <div class="panel-body">
            <% if params[:tag_list_cont].blank? %>
              <%= render @result %>
            <% else %>
              <%= render @tag_search %>
            <% end %>
          </div>
      </div>
    </ol>
  </div>
  <% if params[:tag_list_cont].blank? %>
    <%= paginate @result %>
  <% end %>
</div>

app/views/items/show.html.erb
<br>
<br>
<br>
<div class="items">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="circle-avatar">
        <% if @item.user.avatar? %>
          <%= image_tag @item.user.avatar.url %>
        <% else %>
          <img src="/images/no_avatar.jpg" alt="Chania">
        <% end %>
      </div>
      <%= link_to  @item.user.name, @item.user %>
      <br>
      <span class="content">
        <%= simple_format(@item.content) %>
      </span>
      <%= image_tag @item.picture.url if @item.picture? %>
      <br>
      <%= render 'items/tag_list', tag_list: @item.tag_list %>
      <br>
      <h3>いいね件数: <%= @item.likes.count %></h3>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(@item) %>
          <%= button_to 'いいねを取り消す', item_like_path(@item), method: :delete, class: "btn btn-info btn-sm" %>
        <% else %>
          <%= button_to 'いいね', item_likes_path(@item), class: "btn btn-info btn-sm" %>
        <% end %>
      <% end %>
        <h3>いいねしたユーザー</h3>
        <% @item.liked_users.each do |user| %>
          <li><%= link_to  user.name, user %></li>
        <% end %>


      <% if @item.user == current_user %>
        <%= link_to '編集', edit_item_path , class: 'btn btn-primary mr-3' %>
        <%= link_to '削除', @item, method: :delete, data: { confirm: "投稿を削除してもよろしいですか？"},
                    class: "btn btn-primary mr-3" %>
      <% end %>
      <span class="timestamp">
        <br>
       <%= time_ago_in_words(@item.created_at) %> 前に投稿されました
      </span>
      <br>
      <div class="comment">
        <div id="comments_area">
          <%= render partial: 'comments/index', locals: {comments: @comments } %>
        </div>
        <% if user_signed_in? %>
          <%= render partial: 'comments/form', locals: { comment: @comment, item: @item } %>
        <% end %>
      </div>
    </div>
  </div>
</div>