config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  root 'pages#home'
  get  '/about',   to: 'pages#about'
  resources :users, only: %i(index show)
  resources :items do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <a class="logo" href="/">Majihoji</a>
  <ul>
    <li>© 2019 All rights reserved. All Rights Reserved</li>
    <li>Kanta Nakamura</li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<section class="tophead" role="tophead">
  <header id="header">
    <div class="header-content clearfix">
      <a class="logo" href="/">Majihoji</a>
      <nav class="navigation" role="navigation">
        <ul class="primary-nav">
          <li><%= link_to "Majihojiについて",about_path %></li>
          <li><%= link_to "投稿一覧",   items_path %></li>
          <li><%= link_to "ユーザー覧", users_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "マイページ", user_path(current_user) %></li>
            <li>
              <div class="header_avatar">
                <% if current_user.avatar? %>
                  <%= image_tag current_user.avatar.url %>
                <% else %>
                  <img src="/images/no_avatar.jpg" alt="Chania">
                <% end %>
              </div>
            </li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to '新規登録', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </header>
</section>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<html>
  <head>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Majihoji</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <br>
      <br>
      <br>
      <br>
      <br>
      <%= yield %>
      <%= render 'layouts/footer' %>

      <!-- JS FILES -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <!-- JS FILES -->
    </div>
  </body>
</html>